stages:
  - build

build:
  stage: build
  only:
    - /^release\/.*/
  image: debian:bookworm-slim
  before_script:
    - apt update
    - apt install -y --no-install-recommends g++ build-essential cmake git ca-certificates libssl-dev
  script:
    - cmake -B build -DDELAMETA_BUILD_APP=ON -DDELAMETA_BUILD_TEST=ON -DDELAMETA_APP_BUILD_STATIC=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
    - ctest --test-dir build --output-on-failure
    - cd build && cpack -G DEB
  artifacts:
    paths:
      - build/*.deb

