image: gcc

stages:
  - build
  - test
  - release

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake
  script:
    - mkdir -p build
    - cmake -B build -DDELAMETA_BUILD_APP=ON -DDELAMETA_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Debug
    - cmake --build build -j10
  artifacts:
    paths:
      - build/app/main
      - build/test/test_all
      - build/control
      - build/delameta

test:
  stage: test
  script:
    - ./build/test/test_all

release:
  stage: release
  script:
    - make build-deb -C build
  artifacts:
    paths:
      - build/delameta-1.0.0.deb
