stages:
  - build

build:
  stage: build
  only:
    - /^release\/.*/
  image: debian:bookworm-slim
  before_script:
    - apt update
    - apt install -y --no-install-recommends g++ build-essential cmake git ca-certificates libssl-dev
  script:
    # with lib
    - cmake -B build-dev -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DDELAMETA_BUILD_APP=ON -DDELAMETA_BUILD_TEST=ON -DOPENSSL_USE_STATIC_LIBS=TRUE -DCMAKE_EXE_LINKER_FLAGS="-static"
    - cmake --build build-dev
    - ctest --test-dir build-dev --output-on-failure
    - cd build-dev && cpack -G DEB
    # only executable
    - cmake -B build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=20 -DDELAMETA_BUILD_APP=ON -DDELAMETA_BUILD_TEST=ON -DDELAMETA_INSTALL=OFF -DOPENSSL_USE_STATIC_LIBS=TRUE -DCMAKE_EXE_LINKER_FLAGS="-static"
    - cmake --build build-release
    - ctest --test-dir build-release --output-on-failure
    - cd build-release && cpack -G DEB
  artifacts:
    paths:
      - build-dev/*.deb
      - build-release/*.deb

