stages:
  - build-debian
  - build-ubuntu

build-debian:
  stage: build-debian
  only:
    - /^release\/.*/
  image: debian:bullseye-slim
  before_script:
    - apt update
    - apt install -y --no-install-recommends g++ build-essential ninja-build cmake git ca-certificates libssl-dev
  script:
    - mkdir -p build
    - cmake -B build -G Ninja -DDELAMETA_BUILD_APP=ON -DDELAMETA_BUILD_TEST=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
    - ctest --test-dir build --output-on-failure
    - cmake --build build -t build-deb
  artifacts:
    paths:
      - build-amd64/*.deb

build-ubuntu:
  stage: build-ubuntu
  only:
    - /^release\/.*/
  image: ubuntu:jammy
  before_script:
    - apt update
    - apt install -y --no-install-recommends g++ build-essential ninja-build cmake git ca-certificates libssl-dev
  script:
    - mkdir -p build
    - cmake -B build -G Ninja -DDELAMETA_BUILD_APP=ON -DDELAMETA_BUILD_TEST=ON -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release
    - cmake --build build
    - ctest --test-dir build --output-on-failure
    - cmake --build build -t build-deb
  artifacts:
    paths:
      - build/*.deb

